### ISSUE TITLE
您好，请问如何提取支付宝的健康码

### ISSUE THREAD

**Issue by metanoia1989** [ff4humanity/ff4humanity.github.io#1]
使用 WebViewDebugHook 这个 xposed 插件后，支付包打开对应的健康码，google chrome 调试的页面直接是空白的。

**Comment by ff4humanity** [comment]
大厂的 App 可能做了防护。建议换其他 app 尝试，比如各地自己出的各种政务、民生 app里的健康码小程序。党国的这些地方政府自己做的app都是层层外包粗制滥造的政绩app，基本上没有任何安全防护措施。这个苏康码是我从“我的南京” app 里提取的。
