### ISSUE TITLE
行程码的天数变成7天了

### ISSUE THREAD

**Issue by error1ee** [ff4humanity/ff4humanity.github.io#2]
7月8日，“通信行程卡”微信公众号发布了关于调整“通信行程卡”査询结果覆盖时间范围的公告：根据《新型冠状病毒肺炎防控方案（第九版）》，即日起 “通信行程卡”查询结果的覆盖时间范围由“14天”调整为“7天”。

**Comment by ff4humanity** [comment]
感谢分享。已更新。
